import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  ComponentTreeWidget,
  CompositePanel,
  Designer,
  DesignerToolsWidget,
  HistoryWidget,
  OutlineTreeWidget,
  ResourceWidget,
  SettingsPanel,
  StudioPanel,
  ToolbarPanel,
  ViewPanel,
  ViewToolsWidget,
  ViewportPanel,
  Workbench,
  WorkspacePanel,
} from '@designable/react'
import { createDesigner, GlobalRegistry } from '@designable/core'
import { transformToSchema, transformToTreeNode } from '@designable/formily'
import { SettingsForm } from '@designable/react-settings-form'
import {
  ArrayCards, ArrayTable, Card, Cascader, Checkbox, DatePicker,
  Field, Form, FormCollapse, FormGrid, FormLayout, FormTab,
  Input, NumberPicker, ObjectContainer, Password, Radio, Rate,
  Select, Slider, Space, Switch, Text, TimePicker, Transfer,
  TreeSelect, Upload,
  AllLocales,
} from '@designable/formily-antd'
import { SubmitButton } from '@/designable/SubmitButton'
import { ConfirmDialogButton } from '@/designable/ConfirmDialogButton'
import { ScanTrigger } from '@/designable/ScanTrigger'
import { CardList } from '@/designable/CardList'
import { TableList } from '@/designable/TableList'
import { ActionButton, EventButton, NavigateButton, FeedbackButton } from '@/designable/ActionButtons'
import { CustomButton } from '@/designable/Button'
import { PageHeader, Section, Divider as LayoutDivider, StaticImage, StaticText } from '@/designable/LayoutComponents'
import { Button, message, Modal, Tag, Drawer, Tabs, Select as AntSelect, Radio as AntRadio, Alert } from 'antd'
import JsonEditor from './JsonEditor'
import PreviewPane from './PreviewPane'
import { fieldDefsToSchema, schemaToFieldDefs, normalizeDesignSchema } from './schemaConverter'
import EventsConfigSection from './EventsConfigSection'
import { useInterfaceOptions } from './useInterfaceOptions'
import NodeEventBinder from '@/console/NodeEventBinder'
import type { PageEvent } from '@/runtime/eventTypes'
import type { FieldDef } from '@/runtime/types'
import type { PrinterTemplate } from '@/runtime/printerTypes'

// 注册中文 locale，让属性配置面板显示中文标签
GlobalRegistry.registerDesignerLocales(AllLocales)
GlobalRegistry.setDesignerLanguage('zh-CN')

// transform 命名约定：必须与 createDesigner({ rootComponentName: 'Form' }) 及
// 自定义组件 Resource 的 componentName: 'Field' 对齐，否则 transformToSchema
// 找不到根（默认找 'DesignableForm'）会返回空 schema，导致字段无法识别/保存。
const DESIGNABLE_OPTS = { designableFormName: 'Form', designableFieldName: 'Field' }

const CompositeItem = CompositePanel.Item as any

const componentMap = {
  Form, Field, Input, Select, TreeSelect, Cascader, Radio, Checkbox,
  Slider, Rate, NumberPicker, Transfer, Password, DatePicker, TimePicker,
  Upload, Switch, Text, Card, ArrayCards, ArrayTable, Space, FormTab,
  FormCollapse, FormGrid, FormLayout, ObjectContainer, SubmitButton,
  ConfirmDialogButton, ScanTrigger, CardList, Table: TableList,
  ActionButton, EventButton, NavigateButton, FeedbackButton, CustomButton,
  PageHeader, Section, Divider: LayoutDivider, StaticImage, StaticText,
  DesignableForm: Form, DesignableField: Field,
}

async function authed(path: string, method: string, body?: any) {
  const token = localStorage.getItem('token') || ''
  const resp = await fetch(path, {
    method,
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
    body: body ? JSON.stringify(body) : undefined,
  })
  const data = await resp.json().catch(() => ({}))
  if (!resp.ok) throw new Error(data?.error || `HTTP ${resp.status}`)
  return data
}

export default function PageDesignerPage() {
  const { pageId } = useParams()
  const navigate = useNavigate()
  const [page, setPage] = useState<any>(null)
  const [saving, setSaving] = useState(false)
  const [showJson, setShowJson] = useState(false)
  const [jsonText, setJsonText] = useState('')
  const [jsonErr, setJsonErr] = useState('')
  const [applyingJson, setApplyingJson] = useState(false)
  const [importing, setImporting] = useState(false)
  const autoGenerated = useRef(false)
  const pageDataRef = useRef<any>(null)  // 缓存 pageData 供手动导入用

  // JSON 逃生舱：本地撤回/重做栈（最多 100 步），与画布 history 解耦
  const JSON_HISTORY_MAX = 100
  const jsonUndo = useRef<string[]>([])
  const jsonRedo = useRef<string[]>([])
  const [jsonCanUndo, setJsonCanUndo] = useState(false)
  const [jsonCanRedo, setJsonCanRedo] = useState(false)

  // 预览终端（多端切库）：桌面 antd / 移动 antd-mobile
  const [previewEnd, setPreviewEnd] = useState<'desktop' | 'mobile'>('desktop')
  const [endMode, setEndMode] = useState<'auto' | 'force'>('auto')
  const [endForced, setEndForced] = useState<'desktop' | 'mobile'>('desktop')

  // 事件编排 Drawer（页面级全部事件）
  const [eventsOpen, setEventsOpen] = useState(false)
  const [events, setEvents] = useState<PageEvent[]>([])
  // 预览扫码模拟所需：表单 code（接口调用用 form_code）
  const [formCode, setFormCode] = useState<string>('')
  const [eventFields, setEventFields] = useState<FieldDef[]>([])
  const [eventPrinters, setEventPrinters] = useState<PrinterTemplate[]>([])
  const [savingEvents, setSavingEvents] = useState(false)
  const ifaceOpts = useInterfaceOptions()

  const engine = useMemo(() => {
    const eng = createDesigner({ rootComponentName: 'Form' })
    ;(window as any).__designable_engine__ = eng
    return eng
  }, [])

  /** 等 workspace 就绪后加载 schema（轮询，最多 3 秒） */
  const loadSchemaWhenReady = (schema: any, maxAttempts = 30) => {
    let attempts = 0
    const tryLoad = () => {
      if ((engine as any).workbench?.currentWorkspace) {
        try {
          const sanitized = JSON.parse(JSON.stringify(schema), (k: string, v: any) => {
            if (k === 'enum' && Array.isArray(v)) return v.filter((x: any) => x != null)
            return v
          })
          const tree = (transformToTreeNode as any)(sanitized, DESIGNABLE_OPTS)
          engine.setCurrentTree(tree)
        } catch (e) {
          console.error('Failed to load schema into designer:', e)
          message.warning('布局加载失败，请尝试手动导入')
        }
      } else if (attempts < maxAttempts) {
        attempts++
        setTimeout(tryLoad, 100)
      } else {
        message.warning('设计器未就绪，请点击「导入字段」手动加载')
      }
    }
    setTimeout(tryLoad, 100)
  }

  /** 从 field_definitions 手动导入字段到设计器 */
  const importFromFieldDefs = async () => {
    const pd = pageDataRef.current
    if (!pd) { message.warning('页面数据未加载'); return }
    setImporting(true)
    try {
      // 重新拉取最新 page 数据，确保 field_definitions 是最新的
      const res = await authed(`/api/form-app/pages/${pageId}`, 'GET')
      const latest = res?.data
      const config = latest?.config_json ? JSON.parse(latest.config_json) : {}
      const defs: any[] = config.field_definitions || []
      if (defs.length === 0) { message.warning('字段配置为空，请先在「字段配置」中添加字段'); return }
      const schema = fieldDefsToSchema(defs)
      autoGenerated.current = true
      loadSchemaWhenReady(schema, 5)
      message.success(`已导入 ${defs.length} 个字段`)
    } catch (e: any) {
      message.error(e.message || '导入失败')
    } finally {
      setImporting(false)
    }
  }

  useEffect(() => {
    ;(async () => {
      try {
        const res = await authed(`/api/form-app/pages/${pageId}`, 'GET')
        const pageData = res?.data
        if (!pageData) return
        setPage(pageData)
        pageDataRef.current = pageData

        // 预加载页面事件（供预览扫码模拟开箱即用）+ 解析表单 code
        try {
          const cfg = pageData.config_json ? JSON.parse(pageData.config_json) : {}
          if (Array.isArray(cfg.events)) setEvents(cfg.events)
        } catch { /* 忽略 */ }
        if (pageData.form_app_id) {
          authed(`/api/form-app/infos/${pageData.form_app_id}`, 'GET')
            .then(r => { const code = r?.data?.code; if (code) setFormCode(code) })
            .catch(() => { /* 取不到 code 时预览接口调用降级 */ })
        }

        // 读取多端策略（config_json.end_strategy）
        try {
          const cfg = pageData.config_json ? JSON.parse(pageData.config_json) : {}
          const es = cfg.end_strategy
          if (es && (es.mode === 'auto' || es.mode === 'force')) {
            setEndMode(es.mode)
            if (es.forced === 'desktop' || es.forced === 'mobile') setEndForced(es.forced)
            if (es.mode === 'force' && (es.forced === 'desktop' || es.forced === 'mobile')) {
              setPreviewEnd(es.forced)
            }
          }
        } catch { /* 忽略 */ }

        let schema: any = null

        // 1. 优先加载已有 design_schema（有实际内容时）
        if (pageData.design_schema) {
          try {
            const parsed = normalizeDesignSchema(JSON.parse(pageData.design_schema))
            const hasProps = parsed?.schema?.properties && Object.keys(parsed.schema.properties).length > 0
            if (hasProps) schema = parsed
          } catch { /* 忽略解析失败 */ }
        }

        // 2. 若无有效 design_schema，从 field_definitions 自动生成
        if (!schema) {
          const config = pageData.config_json ? JSON.parse(pageData.config_json) : {}
          const defs: any[] = config.field_definitions || []
          if (defs.length > 0) {
            schema = fieldDefsToSchema(defs)
            autoGenerated.current = true
          }
        }

        if (schema) {
          loadSchemaWhenReady(schema)
        }
      } catch (e: any) {
        message.error(e.message || '加载页面失败')
      }
    })()
  }, [pageId, engine])

  const saveSchema = async () => {
    setSaving(true)
    try {
      const schema = (transformToSchema as any)(engine.getCurrentTree(), DESIGNABLE_OPTS)

      // 将 schema 转换回 field_definitions
      const fieldDefs = schemaToFieldDefs(schema)

      // 读取当前页面的完整配置
      const pageRes = await authed(`/api/form-app/pages/${pageId}`, 'GET')
      const currentConfig = pageRes.data?.config_json ? JSON.parse(pageRes.data.config_json) : {}

      // 更新 field_definitions，保留其他配置（如 scanner）；写入多端策略
      const updatedConfig = {
        ...currentConfig,
        field_definitions: fieldDefs,
        end_strategy: { mode: endMode, forced: endForced },
      }

      // 同时保存 design_schema 和 config_json
      await authed(`/api/form-app/pages/${pageId}`, 'PUT', {
        design_schema: JSON.stringify(schema),
        config_json: JSON.stringify(updatedConfig),
      })

      autoGenerated.current = false
      message.success('布局已保存，字段配置已同步')
    } catch (e: any) {
      message.error(e.message || '保存失败')
    } finally {
      setSaving(false)
    }
  }

  // ── JSON 逃生舱 ─────────────────────────────────────────────────────
  // 打开：把当前画布 schema 序列化进编辑器，重置撤回栈
  const openJson = () => {
    let text = ''
    try {
      const schema = (transformToSchema as any)(engine.getCurrentTree(), DESIGNABLE_OPTS)
      text = JSON.stringify(schema, null, 2)
    } catch {
      text = '{}'
    }
    setJsonText(text)
    setJsonErr('')
    jsonUndo.current = []
    jsonRedo.current = []
    setJsonCanUndo(false)
    setJsonCanRedo(false)
    setShowJson(true)
  }

  // 编辑：每次变更把「上一个值」压入撤回栈（上限 100），清空重做栈
  const onJsonChange = (next: string) => {
    if (next === jsonText) return
    jsonUndo.current.push(jsonText)
    if (jsonUndo.current.length > JSON_HISTORY_MAX) jsonUndo.current.shift()
    jsonRedo.current = []
    setJsonCanUndo(jsonUndo.current.length > 0)
    setJsonCanRedo(false)
    setJsonText(next)
    setJsonErr('')
  }

  const jsonUndoAction = () => {
    if (jsonUndo.current.length === 0) return
    jsonRedo.current.push(jsonText)
    const prev = jsonUndo.current.pop() as string
    setJsonCanUndo(jsonUndo.current.length > 0)
    setJsonCanRedo(true)
    setJsonText(prev)
    setJsonErr('')
  }

  const jsonRedoAction = () => {
    if (jsonRedo.current.length === 0) return
    jsonUndo.current.push(jsonText)
    if (jsonUndo.current.length > JSON_HISTORY_MAX) jsonUndo.current.shift()
    const next = jsonRedo.current.pop() as string
    setJsonCanUndo(true)
    setJsonCanRedo(jsonRedo.current.length > 0)
    setJsonText(next)
    setJsonErr('')
  }

  // 确认应用：校验 JSON → 回灌设计器画布（双向同步）。失败给提示不写入。
  const applyJson = () => {
    let parsed: any
    try {
      parsed = JSON.parse(jsonText)
    } catch (e: any) {
      setJsonErr(`JSON 解析失败：${e.message || '格式不合法'}`)
      return
    }
    // 容忍两种形态：{ form, schema } 整体，或直接的 schema 对象
    const schema = parsed?.schema ? parsed : { schema: parsed }
    setApplyingJson(true)
    try {
      const sanitized = JSON.parse(JSON.stringify(schema), (k: string, v: any) => {
        if (k === 'enum' && Array.isArray(v)) return v.filter((x: any) => x != null)
        return v
      })
      const tree = (transformToTreeNode as any)(sanitized, DESIGNABLE_OPTS)
      engine.setCurrentTree(tree)
      message.success('已应用到画布，可继续编辑或保存')
      setShowJson(false)
    } catch (e: any) {
      setJsonErr(`回灌画布失败：${e.message || '结构不被设计器识别'}`)
    } finally {
      setApplyingJson(false)
    }
  }

  // 打开事件编排 Drawer：拉取当前页 config 的 events/fields/printers
  const openEvents = async () => {
    try {
      const res = await authed(`/api/form-app/pages/${pageId}`, 'GET')
      const cfg = res.data?.config_json ? JSON.parse(res.data.config_json) : {}
      setEvents(Array.isArray(cfg.events) ? cfg.events : [])
      setEventFields(cfg.field_definitions || [])
      setEventPrinters(Array.isArray(cfg.printers) ? cfg.printers : [])
      setEventsOpen(true)
    } catch (e: any) {
      message.error(e.message || '加载事件失败')
    }
  }

  // 仅更新 config_json.events，合并保留其他键（布局 schema 不在 config_json，互不影响）
  const saveEvents = async () => {
    setSavingEvents(true)
    try {
      const res = await authed(`/api/form-app/pages/${pageId}`, 'GET')
      const cfg = res.data?.config_json ? JSON.parse(res.data.config_json) : {}
      const merged = { ...cfg, events }
      await authed(`/api/form-app/pages/${pageId}`, 'PUT', { config_json: JSON.stringify(merged) })
      message.success('事件已保存')
      setEventsOpen(false)
    } catch (e: any) {
      message.error(e.message || '保存事件失败')
    } finally {
      setSavingEvents(false)
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
      <Designer engine={engine} {...({} as any)}>
        <StudioPanel {...({} as any)}>
          <CompositePanel {...({} as any)}>
            <CompositeItem title="组件" icon="Component">
              <ResourceWidget title="页面布局" sources={[PageHeader, Section, LayoutDivider, StaticImage, StaticText]} />
              <ResourceWidget
                title="输入控件"
                sources={[Input, Password, NumberPicker, Rate, Slider, Select, TreeSelect, Cascader, Transfer, Checkbox, Radio, DatePicker, TimePicker, Upload, Switch, ObjectContainer]}
              />
              <ResourceWidget title="布局" sources={[Card, FormGrid, FormTab, FormLayout, FormCollapse, Space]} />
              <ResourceWidget title="数组" sources={[ArrayCards, ArrayTable]} />
              <ResourceWidget title="按钮" sources={[CustomButton, SubmitButton, ActionButton, EventButton, NavigateButton, ConfirmDialogButton]} />
              <ResourceWidget title="展示" sources={[Text]} />
              <ResourceWidget title="业务组件" sources={[ScanTrigger, CardList]} />
            </CompositeItem>
            <CompositeItem title="大纲" icon="Outline">
              <OutlineTreeWidget />
            </CompositeItem>
            <CompositeItem title="历史" icon="History">
              <HistoryWidget />
            </CompositeItem>
          </CompositePanel>

          <Workbench {...({} as any)}>
            <WorkspacePanel {...({} as any)}>
              <ToolbarPanel {...({} as any)}>
                {/* 左侧：返回 + 页面信息 */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, paddingLeft: 4 }}>
                  <Button size="small" onClick={() => navigate(-1)}>← 返回</Button>
                  {page && (
                    <span style={{ fontSize: 13, color: '#666' }}>
                      {page.title}
                      <Tag style={{ marginLeft: 6 }} color="blue">{page.page_type}</Tag>
                      {autoGenerated.current && (
                        <Tag color="orange">已从字段配置自动生成</Tag>
                      )}
                    </span>
                  )}
                </div>

                <DesignerToolsWidget />
                <ViewToolsWidget use={['DESIGNABLE']} />

                {/* 右侧：多端策略 / 导入 / JSON / 事件 / 保存 */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, paddingRight: 8 }}>
                  <span style={{ fontSize: 12, color: '#888' }}>多端</span>
                  <AntSelect
                    size="small"
                    style={{ width: 150 }}
                    value={endMode === 'force' ? `force:${endForced}` : 'auto'}
                    onChange={(v: string) => {
                      if (v === 'auto') { setEndMode('auto') }
                      else { setEndMode('force'); setEndForced(v.endsWith('mobile') ? 'mobile' : 'desktop') }
                    }}
                    options={[
                      { value: 'auto', label: '自动（按终端）' },
                      { value: 'force:desktop', label: '强制桌面' },
                      { value: 'force:mobile', label: '强制移动' },
                    ]}
                  />
                  <AntRadio.Group
                    size="small"
                    value={previewEnd}
                    onChange={e => setPreviewEnd(e.target.value)}
                    optionType="button"
                    buttonStyle="solid"
                  >
                    <AntRadio.Button value="desktop">预览·桌面</AntRadio.Button>
                    <AntRadio.Button value="mobile">预览·移动</AntRadio.Button>
                  </AntRadio.Group>
                  <Button
                    size="small"
                    loading={importing}
                    onClick={importFromFieldDefs}
                    title="从字段配置（字段定义）重新导入字段到设计器"
                  >
                    导入字段
                  </Button>
                  <Button size="small" onClick={openJson}>JSON</Button>
                  <Button size="small" onClick={openEvents}>事件编排</Button>
                  <Button size="small" type="primary" loading={saving} onClick={saveSchema}>
                    保存布局
                  </Button>
                </div>
              </ToolbarPanel>

              <ViewportPanel style={{ height: '100%' }} {...({} as any)}>
                <ViewPanel type="DESIGNABLE" {...({} as any)}>
                  {() => <ComponentTreeWidget components={componentMap} />}
                </ViewPanel>
              </ViewportPanel>
            </WorkspacePanel>
          </Workbench>

          <SettingsPanel title="属性配置" {...({} as any)}>
            <Tabs defaultActiveKey="props" size="small" style={{ padding: '0 8px' }}>
              <Tabs.TabPane key="props" tab="属性">
                <SettingsForm uploadAction="/api/scada/resource/upload/widget" />
              </Tabs.TabPane>
              <Tabs.TabPane key="events" tab="事件">
                <NodeEventBinder pageId={pageId} />
              </Tabs.TabPane>
            </Tabs>
          </SettingsPanel>
        </StudioPanel>
      </Designer>

      <Drawer
        title="事件编排（页面级）"
        visible={eventsOpen}
        onClose={() => setEventsOpen(false)}
        width="80%"
        extra={
          <Button type="primary" loading={savingEvents} onClick={saveEvents}>保存事件</Button>
        }
        bodyStyle={{ background: '#f5f6fa' }}
      >
        <div style={{ marginBottom: 12, color: '#64748b', fontSize: 13 }}>
          配置以本页组件为源的事件流：触发源（扫码 / 自定义事件 / 按钮 / 字段变更）→ 条件 → 动作链。
          按钮组件的「按钮 ID」可在右侧属性区「事件」页签设置后，在此用 source=按钮 关联。
        </div>
        <EventsConfigSection
          events={events}
          onChange={setEvents}
          fields={eventFields}
          printers={eventPrinters}
          interfaceOptions={ifaceOpts.interfaceOptions}
          thirdPartyEndpointOptions={ifaceOpts.thirdPartyEndpointOptions}
          connectorInterfaceOptions={ifaceOpts.connectorInterfaceOptions}
          interfaceSchemas={ifaceOpts.interfaceSchemas}
          thirdPartySchemas={ifaceOpts.thirdPartySchemas}
          connectorSchemas={ifaceOpts.connectorSchemas}
        />
      </Drawer>

      <Modal
        title="JSON 逃生舱（可编辑 / 撤回 / 应用到画布）"
        visible={showJson}
        onCancel={() => setShowJson(false)}
        width={760}
        bodyStyle={{ maxHeight: '72vh', overflow: 'auto' }}
        footer={[
          <Button key="undo" size="small" disabled={!jsonCanUndo} onClick={jsonUndoAction}>撤回</Button>,
          <Button key="redo" size="small" disabled={!jsonCanRedo} onClick={jsonRedoAction}>重做</Button>,
          <Button key="cancel" onClick={() => setShowJson(false)}>关闭</Button>,
          <Button key="apply" type="primary" loading={applyingJson} onClick={applyJson}>确认应用到画布</Button>,
        ]}
      >
        <div style={{ marginBottom: 8, fontSize: 12, color: '#64748b' }}>
          直接编辑 design_schema（{'{ form, schema }'} 或裸 schema 均可）。「确认应用」会校验并回灌画布，
          可继续可视化编辑或点「保存布局」入库。撤回最多 {JSON_HISTORY_MAX} 步（与画布历史相互独立）。
        </div>
        {jsonErr && <Alert type="error" showIcon style={{ marginBottom: 8 }} message={jsonErr} />}
        <JsonEditor value={jsonText} onChange={onJsonChange} minHeight={420} />
      </Modal>

      {/* 预览（多端切库）：跟随顶栏「预览终端」实时渲染 */}
      <PreviewPane
        end={previewEnd}
        events={events}
        onScanInterface={async (interfaceCode, paramValues, type = 'internal', endpointId) => {
          try {
            if (type === 'connector') {
              const res = await authed('/api/outbound/connector-interfaces/call', 'POST', {
                connector_code: interfaceCode,
                params: paramValues,
              })
              return res.data || {}
            }
            if (type === 'third_party') {
              if (!endpointId) throw new Error('endpoint_id is required for third_party interface')
              const res = await authed(`/api/outbound/endpoints/${endpointId}/call`, 'POST', {
                param_values: paramValues,
              })
              return res.data || {}
            }
            const res = await authed('/api/form-app/runtime/submit', 'POST', {
              interface_code: interfaceCode,
              form_code: formCode,
              page_key: page?.page_key,
              param_values: paramValues,
            })
            return res?.data ?? res?.rows ?? res ?? {}
          } catch (e: any) {
            message.warning(`预览调用接口失败：${e?.message || '未知错误'}`)
            return {}
          }
        }}
        getSchema={() => {
          try { return (transformToSchema as any)(engine.getCurrentTree(), DESIGNABLE_OPTS) } catch { return null }
        }}
      />
    </div>
  )
}
