import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  ComponentTreeWidget,
  CompositePanel,
  Designer,
  DesignerToolsWidget,
  HistoryWidget,
  OutlineTreeWidget,
  ResourceWidget,
  SettingsPanel,
  StudioPanel,
  ToolbarPanel,
  ViewPanel,
  ViewToolsWidget,
  ViewportPanel,
  Workbench,
  WorkspacePanel,
} from '@designable/react'
import { createDesigner, GlobalRegistry } from '@designable/core'
import { transformToSchema, transformToTreeNode } from '@designable/formily'
import { SettingsForm } from '@designable/react-settings-form'
import {
  ArrayCards, ArrayTable, Card, Cascader, Checkbox, DatePicker,
  Field, Form, FormCollapse, FormGrid, FormLayout, FormTab,
  Input, NumberPicker, ObjectContainer, Password, Radio, Rate,
  Select, Slider, Space, Switch, Text, TimePicker, Transfer,
  TreeSelect, Upload,
  AllLocales,
} from '@designable/formily-antd'
import { SubmitButton } from '@/designable/SubmitButton'
import { ConfirmDialogButton } from '@/designable/ConfirmDialogButton'
import { Button, message, Modal, Tag } from 'antd'

// 注册中文 locale，让属性配置面板显示中文标签
GlobalRegistry.registerDesignerLocales(AllLocales)
GlobalRegistry.setDesignerLanguage('zh-CN')

const CompositeItem = CompositePanel.Item as any

const componentMap = {
  Form, Field, Input, Select, TreeSelect, Cascader, Radio, Checkbox,
  Slider, Rate, NumberPicker, Transfer, Password, DatePicker, TimePicker,
  Upload, Switch, Text, Card, ArrayCards, ArrayTable, Space, FormTab,
  FormCollapse, FormGrid, FormLayout, ObjectContainer, SubmitButton,
  ConfirmDialogButton, DesignableForm: Form, DesignableField: Field,
}

/** 字段组件名 → Formily 组件名 */
const COMP_MAP: Record<string, string> = {
  Input: 'Input',
  InputNumber: 'NumberPicker',
  NumberPicker: 'NumberPicker',
  Select: 'Select',
  DatePicker: 'DatePicker',
  Switch: 'Switch',
  Rate: 'Rate',
  Slider: 'Slider',
  Checkbox: 'Checkbox',
  Radio: 'Radio',
}

/** 将 config_json.field_definitions 转换为 Formily JSON Schema
 *
 *  每个 property 显式写入 `name` 字段，确保 transformToSchema 能正确还原字段 key。
 */
function fieldDefsToSchema(fieldDefs: any[]): object {
  const properties: Record<string, any> = {}
  fieldDefs.forEach((f, index) => {
    if (!f.field) return
    properties[f.field] = {
      name: f.field,                          // 显式 name，transformToSchema 依赖此字段
      type: 'string',
      title: f.label || f.field,
      'x-decorator': 'FormItem',
      'x-decorator-props': {},
      'x-component': COMP_MAP[f.component] || 'Input',
      'x-component-props': {
        ...(f.placeholder ? { placeholder: f.placeholder } : {}),
      },
      ...(f.required ? { 'x-validator': [{ required: true, message: '此项为必填' }] } : {}),
      'x-index': index,
    }
  })
  return {
    form: { labelCol: 6, wrapperCol: 12 },
    schema: {
      type: 'object',
      properties,
      'x-component': 'FormLayout',
      'x-component-props': { layout: 'vertical' },
    },
  }
}

async function authed(path: string, method: string, body?: any) {
  const token = localStorage.getItem('token') || ''
  const resp = await fetch(path, {
    method,
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
    body: body ? JSON.stringify(body) : undefined,
  })
  const data = await resp.json().catch(() => ({}))
  if (!resp.ok) throw new Error(data?.error || `HTTP ${resp.status}`)
  return data
}

export default function PageDesignerPage() {
  const { pageId } = useParams()
  const navigate = useNavigate()
  const [page, setPage] = useState<any>(null)
  const [saving, setSaving] = useState(false)
  const [showJson, setShowJson] = useState(false)
  const [jsonText, setJsonText] = useState('')
  const [importing, setImporting] = useState(false)
  const autoGenerated = useRef(false)
  const pageDataRef = useRef<any>(null)  // 缓存 pageData 供手动导入用

  const engine = useMemo(() => {
    const eng = createDesigner({ rootComponentName: 'Form' })
    ;(window as any).__designable_engine__ = eng
    return eng
  }, [])

  /** 等 workspace 就绪后加载 schema（轮询，最多 3 秒） */
  const loadSchemaWhenReady = (schema: any, maxAttempts = 30) => {
    let attempts = 0
    const tryLoad = () => {
      if ((engine as any).workbench?.currentWorkspace) {
        try {
          const sanitized = JSON.parse(JSON.stringify(schema), (k: string, v: any) => {
            if (k === 'enum' && Array.isArray(v)) return v.filter((x: any) => x != null)
            return v
          })
          const tree = (transformToTreeNode as any)(sanitized)
          engine.setCurrentTree(tree)
        } catch (e) {
          console.error('Failed to load schema into designer:', e)
          message.warning('布局加载失败，请尝试手动导入')
        }
      } else if (attempts < maxAttempts) {
        attempts++
        setTimeout(tryLoad, 100)
      } else {
        message.warning('设计器未就绪，请点击「导入字段」手动加载')
      }
    }
    setTimeout(tryLoad, 100)
  }

  /** 从 field_definitions 手动导入字段到设计器 */
  const importFromFieldDefs = async () => {
    const pd = pageDataRef.current
    if (!pd) { message.warning('页面数据未加载'); return }
    setImporting(true)
    try {
      // 重新拉取最新 page 数据，确保 field_definitions 是最新的
      const res = await authed(`/api/form-app/pages/${pageId}`, 'GET')
      const latest = res?.data
      const config = latest?.config_json ? JSON.parse(latest.config_json) : {}
      const defs: any[] = config.field_definitions || []
      if (defs.length === 0) { message.warning('字段配置为空，请先在「字段配置」中添加字段'); return }
      const schema = fieldDefsToSchema(defs)
      autoGenerated.current = true
      loadSchemaWhenReady(schema, 5)
      message.success(`已导入 ${defs.length} 个字段`)
    } catch (e: any) {
      message.error(e.message || '导入失败')
    } finally {
      setImporting(false)
    }
  }

  useEffect(() => {
    ;(async () => {
      try {
        const res = await authed(`/api/form-app/pages/${pageId}`, 'GET')
        const pageData = res?.data
        if (!pageData) return
        setPage(pageData)
        pageDataRef.current = pageData

        let schema: any = null

        // 1. 优先加载已有 design_schema（有实际内容时）
        if (pageData.design_schema) {
          try {
            const parsed = JSON.parse(pageData.design_schema)
            const hasProps = parsed?.schema?.properties && Object.keys(parsed.schema.properties).length > 0
            if (hasProps) schema = parsed
          } catch { /* 忽略解析失败 */ }
        }

        // 2. 若无有效 design_schema，从 field_definitions 自动生成
        if (!schema) {
          const config = pageData.config_json ? JSON.parse(pageData.config_json) : {}
          const defs: any[] = config.field_definitions || []
          if (defs.length > 0) {
            schema = fieldDefsToSchema(defs)
            autoGenerated.current = true
          }
        }

        if (schema) {
          loadSchemaWhenReady(schema)
        }
      } catch (e: any) {
        message.error(e.message || '加载页面失败')
      }
    })()
  }, [pageId, engine])

  const saveSchema = async () => {
    setSaving(true)
    try {
      const schema = (transformToSchema as any)(engine.getCurrentTree())
      await authed(`/api/form-app/pages/${pageId}`, 'PUT', {
        design_schema: JSON.stringify(schema),
      })
      autoGenerated.current = false
      message.success('布局已保存')
    } catch (e: any) {
      message.error(e.message || '保存失败')
    } finally {
      setSaving(false)
    }
  }

  const showJsonPreview = () => {
    try {
      const schema = (transformToSchema as any)(engine.getCurrentTree())
      setJsonText(JSON.stringify(schema, null, 2))
    } catch {
      setJsonText('/* 解析失败 */')
    }
    setShowJson(true)
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
      <Designer engine={engine}>
        <StudioPanel>
          <CompositePanel>
            <CompositeItem title="组件" icon="Component">
              <ResourceWidget
                title="输入控件"
                sources={[Input, Password, NumberPicker, Rate, Slider, Select, TreeSelect, Cascader, Transfer, Checkbox, Radio, DatePicker, TimePicker, Upload, Switch, ObjectContainer]}
              />
              <ResourceWidget title="布局" sources={[Card, FormGrid, FormTab, FormLayout, FormCollapse, Space]} />
              <ResourceWidget title="数组" sources={[ArrayCards, ArrayTable]} />
              <ResourceWidget title="展示" sources={[Text, SubmitButton, ConfirmDialogButton]} />
            </CompositeItem>
            <CompositeItem title="大纲" icon="Outline">
              <OutlineTreeWidget />
            </CompositeItem>
            <CompositeItem title="历史" icon="History">
              <HistoryWidget />
            </CompositeItem>
          </CompositePanel>

          <Workbench>
            <WorkspacePanel>
              <ToolbarPanel>
                {/* 左侧：返回 + 页面信息 */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, paddingLeft: 4 }}>
                  <Button size="small" onClick={() => navigate(-1)}>← 返回</Button>
                  {page && (
                    <span style={{ fontSize: 13, color: '#666' }}>
                      {page.title}
                      <Tag style={{ marginLeft: 6 }} color="blue">{page.page_type}</Tag>
                      {autoGenerated.current && (
                        <Tag color="orange">已从字段配置自动生成</Tag>
                      )}
                    </span>
                  )}
                </div>

                <DesignerToolsWidget />
                <ViewToolsWidget use={['DESIGNABLE']} />

                {/* 右侧：导入 / 保存 / JSON预览 */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, paddingRight: 8 }}>
                  <Button
                    size="small"
                    loading={importing}
                    onClick={importFromFieldDefs}
                    title="从字段配置（字段定义）重新导入字段到设计器"
                  >
                    导入字段
                  </Button>
                  <Button size="small" onClick={showJsonPreview}>JSON</Button>
                  <Button size="small" type="primary" loading={saving} onClick={saveSchema}>
                    保存布局
                  </Button>
                </div>
              </ToolbarPanel>

              <ViewportPanel style={{ height: '100%' }}>
                <ViewPanel type="DESIGNABLE">
                  {() => <ComponentTreeWidget components={componentMap} />}
                </ViewPanel>
              </ViewportPanel>
            </WorkspacePanel>
          </Workbench>

          <SettingsPanel title="属性配置">
            <SettingsForm uploadAction="/api/scada/resource/upload/widget" />
          </SettingsPanel>
        </StudioPanel>
      </Designer>

      <Modal
        title="Design Schema JSON"
        visible={showJson}
        onCancel={() => setShowJson(false)}
        footer={null}
        width={700}
        bodyStyle={{ maxHeight: '70vh', overflow: 'auto' }}
      >
        <pre style={{ margin: 0, fontSize: 12, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
          {jsonText}
        </pre>
      </Modal>
    </div>
  )
}
